import { CountryRegion } from "../types/serviceTypes";

const countriesWithRegions: CountryRegion[] = [
    { country: "Australia", region: "Australasia & Oceania" },
    { country: "New Zealand", region: "Australasia & Oceania" },
    { country: "Papua New Guinea", region: "Australasia & Oceania" },
    { country: "Solomon Islands", region: "Australasia & Oceania" },
    { country: "Vanuatu", region: "Australasia & Oceania" },
    { country: "Fiji", region: "Australasia & Oceania" },
    { country: "Samoa", region: "Australasia & Oceania" },
    { country: "Tonga", region: "Australasia & Oceania" },
    { country: "Antigua and Barbuda", region: "Central America & Caribbean" },
    { country: "Bahamas", region: "Central America & Caribbean" },
    { country: "Belize", region: "Central America & Caribbean" },
    { country: "Cuba", region: "Central America & Caribbean" },
    { country: "Dominica", region: "Central America & Caribbean" },
    { country: "El Salvador", region: "Central America & Caribbean" },
    { country: "Grenada", region: "Central America & Caribbean" },
    { country: "Honduras", region: "Central America & Caribbean" },
    { country: "Jamaica", region: "Central America & Caribbean" },
    { country: "Nicaragua", region: "Central America & Caribbean" },
    { country: "Panama", region: "Central America & Caribbean" },
    { country: "Saint Lucia", region: "Central America & Caribbean" },
    { country: "Saint Vincent and the Grenadines", region: "Central America & Caribbean" },
    { country: "Kazakhstan", region: "Central Asia" },
    { country: "Kyrgyzstan", region: "Central Asia" },
    { country: "Tajikistan", region: "Central Asia" },
    { country: "Turkmenistan", region: "Central Asia" },
    { country: "Uzbekistan", region: "Central Asia" },
    { country: "China", region: "East Asia" },
    { country: "Japan", region: "East Asia" },
    { country: "South Korea", region: "East Asia" },
    { country: "North Korea", region: "East Asia" },
    { country: "Mongolia", region: "East Asia" },
    { country: "Albania", region: "Eastern Europe" },
    { country: "Bulgaria", region: "Eastern Europe" },
    { country: "Hungary", region: "Eastern Europe" },
    { country: "Poland", region: "Eastern Europe" },
    { country: "Romania", region: "Eastern Europe" },
    { country: "Serbia", region: "Eastern Europe" },
    { country: "Slovakia", region: "Eastern Europe" },
    { country: "Slovenia", region: "Eastern Europe" },
    { country: "Ukraine", region: "Eastern Europe" },
    { country: "Moldova", region: "Eastern Europe" },
    { country: "Czech Republic", region: "Eastern Europe" },
    { country: "North Macedonia", region: "Eastern Europe" },
    { country: "Algeria", region: "Middle East & North Africa" },
    { country: "Egypt", region: "Middle East & North Africa" },
    { country: "Iraq", region: "Middle East & North Africa" },
    { country: "Jordan", region: "Middle East & North Africa" },
    { country: "Lebanon", region: "Middle East & North Africa" },
    { country: "Libya", region: "Middle East & North Africa" },
    { country: "Morocco", region: "Middle East & North Africa" },
    { country: "Sudan", region: "Middle East & North Africa" },
    { country: "Syria", region: "Middle East & North Africa" },
    { country: "Tunisia", region: "Middle East & North Africa" },
    { country: "Saudi Arabia", region: "Middle East & North Africa" },
    { country: "Kuwait", region: "Middle East & North Africa" },
    { country: "Bahrain", region: "Middle East & North Africa" },
    { country: "Qatar", region: "Middle East & North Africa" },
    { country: "United Arab Emirates", region: "Middle East & North Africa" },
    { country: "Oman", region: "Middle East & North Africa" },
    { country: "Yemen", region: "Middle East & North Africa" },
    { country: "Palestine", region: "Middle East & North Africa" },
    { country: "Israel", region: "Middle East & North Africa" },
    { country: "Canada", region: "North America" },
    { country: "United States", region: "North America" },
    { country: "Mexico", region: "North America" },
    { country: "Argentina", region: "South America" },
    { country: "Bolivia", region: "South America" },
    { country: "Brazil", region: "South America" },
    { country: "Chile", region: "South America" },
    { country: "Colombia", region: "South America" },
    { country: "Ecuador", region: "South America" },
    { country: "Guyana", region: "South America" },
    { country: "Paraguay", region: "South America" },
    { country: "Peru", region: "South America" },
    { country: "Suriname", region: "South America" },
    { country: "Uruguay", region: "South America" },
    { country: "Venezuela", region: "South America" },
    { country: "Afghanistan", region: "South Asia" },
    { country: "Bangladesh", region: "South Asia" },
    { country: "Bhutan", region: "South Asia" },
    { country: "India", region: "South Asia" },
    { country: "Maldives", region: "South Asia" },
    { country: "Nepal", region: "South Asia" },
    { country: "Pakistan", region: "South Asia" },
    { country: "Sri Lanka", region: "South Asia" },
    { country: "Brunei", region: "Southeast Asia" },
    { country: "Cambodia", region: "Southeast Asia" },
    { country: "Indonesia", region: "Southeast Asia" },
    { country: "Laos", region: "Southeast Asia" },
    { country: "Malaysia", region: "Southeast Asia" },
    { country: "Myanmar", region: "Southeast Asia" },
    { country: "Philippines", region: "Southeast Asia" },
    { country: "Singapore", region: "Southeast Asia" },
    { country: "Timor-Leste", region: "Southeast Asia" },
    { country: "Thailand", region: "Southeast Asia" },
    { country: "Vietnam", region: "Southeast Asia" },
    { country: "Angola", region: "Sub-Saharan Africa" },
    { country: "Botswana", region: "Sub-Saharan Africa" },
    { country: "Benin", region: "Sub-Saharan Africa" },
    { country: "Burkina Faso", region: "Sub-Saharan Africa" },
    { country: "Burundi", region: "Sub-Saharan Africa" },
    { country: "Cameroon", region: "Sub-Saharan Africa" },
    { country: "Cape Verde", region: "Sub-Saharan Africa" },
    { country: "Chad", region: "Sub-Saharan Africa" },
    { country: "Comoros", region: "Sub-Saharan Africa" },
    { country: "Democratic Republic of the Congo", region: "Sub-Saharan Africa" },
    { country: "Gabon", region: "Sub-Saharan Africa" },
    { country: "Gambia", region: "Sub-Saharan Africa" },
    { country: "Ghana", region: "Sub-Saharan Africa" },
    { country: "Guinea", region: "Sub-Saharan Africa" },
    { country: "Guinea-Bissau", region: "Sub-Saharan Africa" },
    { country: "Ivory Coast", region: "Sub-Saharan Africa" },
    { country: "Kenya", region: "Sub-Saharan Africa" },
    { country: "Lesotho", region: "Sub-Saharan Africa" },
    { country: "Liberia", region: "Sub-Saharan Africa" },
    { country: "Mauritius", region: "Sub-Saharan Africa" },
    { country: "Malawi", region: "Sub-Saharan Africa" },
    { country: "Mauritania", region: "Sub-Saharan Africa" },
    { country: "Namibia", region: "Sub-Saharan Africa" },
    { country: "Niger", region: "Sub-Saharan Africa" },
    { country: "Nigeria", region: "Sub-Saharan Africa" },
    { country: "Republic of the Congo", region: "Sub-Saharan Africa" },
    { country: "Rwanda", region: "Sub-Saharan Africa" },
    { country: "Seychelles", region: "Sub-Saharan Africa" },
    { country: "Somalia", region: "Sub-Saharan Africa" },
    { country: "South Sudan", region: "Sub-Saharan Africa" },
    { country: "Swaziland", region: "Sub-Saharan Africa" },
    { country: "Tanzania", region: "Sub-Saharan Africa" },
    { country: "Togo", region: "Sub-Saharan Africa" },
    { country: "Uganda", region: "Sub-Saharan Africa" },
    { country: "Zambia", region: "Sub-Saharan Africa" },
    { country: "Zimbabwe", region: "Sub-Saharan Africa" },
  ];
  
  export default countriesWithRegions